### ISSUE TITLE
Settings keeps stopping

### ISSUE THREAD

**Issue by DaAngus** [WeAreFairphone/android_device_fairphone_FP3#17]
Navigate to Settings - Security & location and select Location: The Settings application crashes.

If its not reproducible I will add Details as good as I can.

**Comment by mstaz** [comment]
Do you use the microG version or the clean one?

**Comment by DaAngus** [comment]
microG, Location works in OSMAnd. Its just the Settings.
I have had problems with the clean Version as it could not resolve some paths.
So you can not reproduce it?

**Comment by mstaz** [comment]
No, for me this settings screen works fine with the microG version.
Did you configure UnifiedNlp in the microG settings and is the self-check ok?

**Comment by DaAngus** [comment]
I have it configured and the self-check seems ok.
I changed nothing(tm) and now it works. 
Can't reproduce, closed.
Thanks for taking your time

**Comment by DaAngus** [comment]
Spoke to soon, this is strange:

If I open Settings and go straight to "Security & location - location" it crashes.

If I open Settings and go to "System - Advanced - microG Settings" have a look and go back, now I can access "Security & location - location" without a crash.

**Comment by paalsteek** [comment]
I was able to pull the following log after the location menu crashed.
EDIT: This seems to be related to microg/android_packages_apps_UnifiedNlp#165.

```
07-04 20:06:02.255 17591 17591 D SettingsActivity: Switching to fragment com.android.settings.location.LocationSettings
07-04 20:06:02.255 17591 17591 D SubSettings: Launching fragment com.android.settings.location.LocationSettings
07-04 20:06:02.258  1120 14733 E UserRestrictionsUtils: Unknown restriction: null
07-04 20:06:02.264 17591 17591 D LocationSettings: NO dashboard tiles for LocationSettings
07-04 20:06:02.264 17591 17591 D SettingsActivity: Executed frag manager pendingTransactions
07-04 20:06:02.276 17591 17609 I DeviceIndex: Skipping: device index is not enabled
07-04 20:06:02.278 17591 17591 I LocationEnabler: Location mode has been changed
07-04 20:06:02.278 17591 17607 W TileUtils: Found com.android.settings.Settings$NotificationAppListActivity for intent Intent { act=com.android.settings.action.SETTINGS pkg=com.android.settings } missing metadata com.android.settings.category
07-04 20:06:02.280 17591 17607 W TileUtils: Found org.lineageos.lineageparts.trust.TrustPreferences for intent Intent { act=org.lineageos.lineageparts.action.SETTINGS pkg=org.lineageos.lineageparts } missing metadata 
07-04 20:06:02.282 17591 17591 I LocationEnabler: Location mode has been changed
07-04 20:06:02.286 17591 17591 I chatty  : uid=1000(system) com.android.settings identical 3 lines
07-04 20:06:02.286 17591 17591 I LocationEnabler: Location mode has been changed
07-04 20:06:02.287 17591 17607 D SettingsActivity: No enabled state changed, skipping updateCategory call
07-04 20:06:02.401  1120 14733 W ActivityManager: Background start not allowed: service Intent { cmp=com.google.android.gms/org.microg.nlp.ui.SettingInjectorService (has extras) } to com.google.android.gms/org.microg.nlp.ui.SettingInjectorService from pid=17591 uid=1000 pkg=com.android.settings startFg?=false
07-04 20:06:02.402 17591 17591 D AndroidRuntime: Shutting down VM
07-04 20:06:02.403 17591 17591 E AndroidRuntime: FATAL EXCEPTION: main
07-04 20:06:02.403 17591 17591 E AndroidRuntime: Process: com.android.settings, PID: 17591
07-04 20:06:02.403 17591 17591 E AndroidRuntime: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.google.android.gms/org.microg.nlp.ui.SettingInjectorService (has extras) }: app is in background uid UidRecord{24c910e u10a3 CEM  idle change:cached procs:1 seq(0,0,0)}
07-04 20:06:02.403 17591 17591 E AndroidRuntime:        at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1577)
07-04 20:06:02.403 17591 17591 E AndroidRuntime:        at android.app.ContextImpl.startServiceAsUser(ContextImpl.java:1549)
07-04 20:06:02.403 17591 17591 E AndroidRuntime:        at android.content.ContextWrapper.startServiceAsUser(ContextWrapper.java:680)
07-04 20:06:02.403 17591 17591 E AndroidRuntime:        at com.android.settings.location.SettingsInjector$Setting.startService(SettingsInjector.java:561)
07-04 20:06:02.403 17591 17591 E AndroidRuntime:        at com.android.settings.location.SettingsInjector$StatusLoadingHandler.handleMessage(SettingsInjector.java:457)
07-04 20:06:02.403 17591 17591 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
07-04 20:06:02.403 17591 17591 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:193)
07-04 20:06:02.403 17591 17591 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6718)
07-04 20:06:02.403 17591 17591 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
07-04 20:06:02.403 17591 17591 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
07-04 20:06:02.403 17591 17591 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
07-04 20:06:02.408  1120 14733 W ActivityManager:   Force finishing activity com.android.settings/.SubSettings
07-04 20:06:02.412  1120 14733 W ActivityManager:   Force finishing activity com.android.settings/.Settings$SecurityDashboardActivity
07-04 20:06:02.415  1120  1303 I ActivityManager: Showing crash dialog for package com.android.settings u0
```

**Comment by dk1978** [comment]
I cannot reproduce this, sorry. I assume that it is up to the MicroG people to fix this.
